### ISSUE TITLE
The `methods` tables are broken everywhere.

### ISSUE THREAD

**Issue by MrChebur** [qgis/pyqgis#100]
The `methods` tables are broken everywhere. Examples:
https://qgis.org/pyqgis/3.28/core/QgsVectorLayer.html#grass-data-provider-grass
https://qgis.org/pyqgis/3.28/core/QgsVectorLayerFeatureCounter.html
![1](https://user-images.githubusercontent.com/20655102/199657415-1ac1a305-2588-4a65-90de-cc6784c2a6ee.png)
![2](https://user-images.githubusercontent.com/20655102/199657418-40f1641a-b94b-438e-839b-c4433f769498.png)

**Comment by MrChebur** [comment]
Fixed (somehow).

**Comment by DelazJ** [comment]
somehow indeed... see https://github.com/qgis/QGIS/issues/50903
