### ISSUE TITLE
imports is not defined in make_api_rst

### ISSUE THREAD

**Issue by ghtmtt** [qgis/pyqgis#102]
I've noticed that the variable `imports`: https://github.com/qgis/pyqgis/blob/master/scripts/make_api_rst.py#L24 is not defined in the script. So when choosing an argument to the `-p` parameter I got this error:

```bash
~/dev/pyqgis ~/dev/pyqgis
QGIS VERSION: master
PACKAGE LIMIT: --package analysis
setting PYTHONPATH :/home/matteo/dev/pyqgis/scripts/..
##[group]make API RST ./scripts/make_api_rst.py --package analysis  -v master
Traceback (most recent call last):
  File "/home/matteo/dev/pyqgis/./scripts/make_api_rst.py", line 24, in <module>
    exec("from qgis import {}".format(', '.join(imports)))
NameError: name 'imports' is not defined
```

with the `-c` parameter the flow is correctly working.

@3nids Am I doing something wrong?

**Comment by 3nids** [comment]
@ghtmtt can you try with master?

**Comment by ghtmtt** [comment]
seems the same. I added the `-v master` parameter and I also edited the `pyqgis_conf.yml` file leaving only the master tag
