### ISSUE TITLE
Improve usability of side column on the left: make the search field a fixed panel

### ISSUE THREAD

**Issue by andreasneumann** [qgis/pyqgis#103]
The list of QGIS classes is extremely long. It almost feels like "infinite scrolling" ;-)

I guess people work a lot with the "search" field, but after clicking on a search result, the API doc scrolls down a lot in the left class list (expected and useful) - and if the user wants to search for another class, he has to scroll very long to return back to the search field.

Option 1:
It would be very useful if the top blue part of the side column wouldn't scroll with the rest of the class list (remain static):

![image](https://user-images.githubusercontent.com/884476/207828056-11b2fb3c-8398-475c-9ab5-f0f29507cad8.png)

Option 2:
If option 1 isn't possible, could we add a a little button on the bottom left (the black part that remains static), that would allow users to scroll up to the search field with one single click, instead of having to scroll for ages?

![image](https://user-images.githubusercontent.com/884476/207829417-357894ca-2674-42c9-93c1-e0b9feb6344b.png)

Something like:
![image](https://user-images.githubusercontent.com/884476/207829596-5687a250-d297-4477-a3e8-635c552e15e9.png)

**Comment by DelazJ** [comment]
Option3
Add a search box in the bottom field, as in the [readthedocs docs](https://docs.readthedocs.io/en/stable/index.html) though not easily discoverable as option 2 (but probably easier to implement)
![image](https://user-images.githubusercontent.com/7983394/207832980-a07e5773-edd7-4f66-ba97-c7fefb6a4752.png)

**Comment by ghtmtt** [comment]
@andreasneumann with https://github.com/qgis/pyqgis/pull/101 we have a scrollbar. It isn't solving completely the issue (I agree with the "Go to top" button) but is better than nothing :)

**Comment by andreasneumann** [comment]
@DelazJ - yes, this option 3 would also be fine. I am happy with either improvement.

@ghtmtt - thanks. This is also an improvement. Better than before, without the scrollbar.

Thanks!

**Comment by ghtmtt** [comment]
I think we can close this issue.
