### ISSUE TITLE
PyQGIS docs is getting too large (>10gb)

### ISSUE THREAD

**Issue by DelazJ** [qgis/pyqgis#104]
Last build of master is 2 days old, one more for 3.22 and 3.28 and the deploy action seems to be failing (https://github.com/qgis/pyqgis/actions/runs/3710014166/jobs/6289253815#step:2:78 or https://github.com/qgis/pyqgis/deployments)

**Comment by 3nids** [comment]
bigger than 10gb!!!!
I'll have a look, cheers!

**Comment by 3nids** [comment]
I just deleted all the pages of the pull request preview.
I guess it will help for a bit but it won't solve the issue on the long term.

Shall we avoid publishing all the versions of the API from 3.0.
We could maybe keep a static version of old versions which would be downloadable as an archive?
That would also avoid the web search engines to lead people to outdated docs.
We could keep only LTR, PR and master.

**Comment by DelazJ** [comment]
Thanks @3nids for the cleanup
>I just deleted all the pages of the pull request preview.
I guess it will help for a bit but it won't solve the issue on the long term.

Would that make sense/worth it to have an action that deletes the pages once the PR is merged/closed? (maybe, not enough traffic for automation, we can do it manually)

Providing an archive of old versions would probably make sense (and if it helps reduce the size of the repo, GREAT!)

**Comment by DelazJ** [comment]
@3nids We again reached the 10GB size of github pages so cleanup is necessary. TIA.

**Comment by 3nids** [comment]
@DelazJ let's meet to discusss what is the best approach?

**Comment by 3nids** [comment]
I went for a light approach where only master, stable and ltr versions of the docs are available online.
Olders versions of the API docs will be accessible through releases in this repo: 

Fixed by https://github.com/qgis/pyqgis/commit/e92253bcb7e839542c50ed1b5de67e3fc6cfd4f8 and following commits https://github.com/qgis/pyqgis/releases

**Comment by kannes** [comment]
Could we get a custom 404 page that points users to that download page?
