### ISSUE TITLE
latest is pointing to 3.16 API

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/pyqgis#108]
As the title suggests 

https://qgis.org/pyqgis/latest/

Is pointing to 

https://qgis.org/pyqgis/3.16/

and not

https://qgis.org/pyqgis/3.22/

**Comment by jef-n** [comment]
> Still true. @jef-n @3nids @timlinux @rduivenvoorde in the case you would know on what server that redirection is set up... Thanks

No idea - but that did remind me to add https://qgis.org/api/3.30.  Thanks.

**Comment by jef-n** [comment]
Fixed on www2.qgis.org

**Comment by SrNetoChan** [comment]
Thanks @jef-n !!
