### ISSUE TITLE
Search bar is not working

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/pyqgis#109]
For more recent versions of the PyQGIS API, the search bar is not working. Keeps spinning but does not retrieve any results.

**Comment by DelazJ** [comment]
See also https://www.mail-archive.com/qgis-developer@lists.osgeo.org/msg54770.html
I'm quite curious of what version of sphinx and readthedocs theme the PyQGIS docs is built over...

**Comment by ghtmtt** [comment]
I cannot find in this repo where the installation libraries are set. @3nids do you have any clue?

**Comment by ghtmtt** [comment]
seems we are still stuck here. I don't think this problem is related to https://github.com/qgis/pyqgis/commit/465d915555a265e4f1828f0da623d32f8ac7a1de because it was working for a while. But if someone thinks it is, I'll revert it.

As @DelazJ said, I'm also curious of the sphinx and readthedocs version of the pyqgis docs, because the JQuery should be shipped with the theme itself.

I've tried with a PR (https://github.com/qgis/pyqgis/pull/110). can we see the build of a PR somewhere to see if it is working?

**Comment by DelazJ** [comment]
@ghtmtt build will be available at https://github.com/qgis/pyqgis/tree/gh-pages

**Comment by ghtmtt** [comment]
@DelazJ no I mean if there is an *interactive* build, like those that we have at the standard website, but just for a PR

**Comment by DelazJ** [comment]
Well, https://qgis.org/pyqgis/master_PR110 it is, once the build is finished.

**Comment by DelazJ** [comment]
See also https://github.com/readthedocs/sphinx_rtd_theme/issues/1434 assuming we are using rtd 1.2.0 because Richard reported the bug the day after they release it.

**Comment by ghtmtt** [comment]
@DelazJ the build failed, I have no idea why: https://github.com/qgis/pyqgis/actions/runs/4230301584/jobs/7347477245#step:3:18337

@3nids do you have any clue?

**Comment by DelazJ** [comment]
@ghtmtt try with a branch from within the qgis repo. Not from your fork.

**Comment by ghtmtt** [comment]
done, thanks! Let's see...

**Comment by 3nids** [comment]
it's there now, it takes some time by github pages to get digested

**Comment by ghtmtt** [comment]
ops sorry, too fast. Anyway, it is still not working :( 

I'm going out of ideas. Should we wait the fix upstream that @DelazJ pointed out (https://github.com/readthedocs/sphinx_rtd_theme/issues/1434)?

**Comment by ghtmtt** [comment]
making some test on another repository on gitlab and published with the gitlab pages where I have the same problem with the searchbar, I was able to fix it by adding the `'sphinxcontrib-jquery'` extension. Trying to add it also to the PR
