### ISSUE TITLE
Lighten `index.html` for faster loading time

### ISSUE THREAD

**Issue by nicogodet** [qgis/pyqgis#116]
Currently, https://qgis.org/pyqgis/master/index.html takes a relatively long time to load (6s on my machine, chrome, fiber internet)
![image](https://user-images.githubusercontent.com/39594821/224287975-8a2a04ec-2a3e-473e-9a8f-f127ce29c4ad.png)

This index page list all pyqgis classes and discussed with other users on this page, we all use the search bar instead of scrolling in index page.
Replacing the listing with a nice welcome message like https://api.qgis.org/api/master/ would be a nice to have improvement.

**Comment by kannes** [comment]
Oh yes, I even had it freeze my browser for many more seconds recently during workshops.
This would be a great change.

**Comment by nicogodet** [comment]
https://github.com/qgis/pyqgis/blob/5ef7563c2ca5476f552d3fc19716780e52dba5b7/scripts/make_api_rst.py#L33-L43

Reducing the maxdepth ou tocdepth (don't know which influence what) to 1 (or 2) would be enough ?

**Comment by DelazJ** [comment]
See PRs in action at https://qgis.org/pyqgis/master_PR120 and https://qgis.org/pyqgis/master_PR121
