### ISSUE TITLE
Segmentation fault when calling getFeatures on layer - but only if qgis init is placed in a different function

### ISSUE THREAD

**Issue by velle** [qgis/pyqgis#117]
It took me ages to figure out why my very simple stand alone script kept crashing when getFeatures was called, when very similar code had worked without issues for me in other cases. After hours of experimenting I found out that somehow, when I placed the code for initializing qgis and loading the project in a separate function and returned the project object, it failed, but if I placed that code in the same function it worked as expected. 

```
from qgis.core import QgsApplication, QgsProject
PATH = 'test.qgz'

def method1(): # goes well
    QgsApplication.setPrefixPath("/usr", True)
    qgs = QgsApplication([], False)
    qgs.initQgis()

    project = QgsProject.instance()
    project.read(PATH)

    lyr = project.mapLayersByName('cables')[0]
    assert lyr.isValid()
    lyr.getFeatures() # goes well


def openqgisproj():
    QgsApplication.setPrefixPath("/usr", True)
    qgs = QgsApplication([], False)
    qgs.initQgis()

    project = QgsProject.instance()
    project.read(PATH)
    return project

def method2(): # fails
    project = openqgisproj()

    lyr = project.mapLayersByName('cables')[0]
    assert lyr.isValid()
    lyr.getFeatures() # crashes here

if __name__ == '__main__':
    method2()

```

**The output produced when crashing is:**

```
QEventLoop: Cannot be used without QApplication
Segmentation fault (core dumped)
```
However, I believe the first line is unrelated since this is sometimes printed without any crash. 

**Environment:**
```
3.22.4-Białowieża
Ubuntu 22.04.2 LTS
```

Please let me know if you need more information.

**Comment by nicogodet** [comment]
It's related to local variable inside function in Python...
In `openqgisproj` you initialize QGIS but it does not persist after the return 

```python
def test():
    a = 1
    b = 2
    return b

>>> test()
2
>>> print(a)
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
NameError: name 'a' is not defined
```

You need to go back to python basics.
Not a QGIS issue.

**Comment by velle** [comment]
Thanks for replying. The example you supplied is indeed Python basics. 

But in my understanding your example is entirely different from what I posted. No where in my code example do I use a variable that is not defined in that scope. Whether an object persists and whether the variable/object is available in a given scope are two different things. 

I am guessing that some resources are cleaned up after exiting the scope of openqgisproject, which is why it fails. But if the project object depends on the qgs object, then the qgs object should not be cleaned up before project is cleaned up. 

The fact that the qgs object is cleaned up before other objects that depend on qgs are cleaned up appears to me to be a bug.

**Comment by nicogodet** [comment]
AFAIK, it's how Python works, not QGIS.
