### ISSUE TITLE
disabling SSL verification

### ISSUE THREAD

**Issue by userVF** [qgis/pyqgis#118]
Hi All!
Sorry, I did not find `Discussion` section, so let me ask my question here.

I use `Python Console` to request `https://some-site.com` like this:
```
def init_request(self):  
    req = ...    
    self.nam = QtNetwork.QNetworkAccessManager()
    self.nam.finished.connect(self.handle_response)        
    self.nam.get(req)
    
def handle_response(self, reply): 
    if reply.error() != QtNetwork.QNetworkReply.NoError:
        print(reply.errorString())
        return
```
`reply.errorString()` outputs `SSL handshake failed` because  the `https://some-site.com`  has problem with SSL certificate.
Is there a way to disable the SSL verification?

Thanks!

**Comment by nicogodet** [comment]
This has nothing to deal with QGIS. It's pure Qt.

**Comment by userVF** [comment]
Ok, I got it
