### ISSUE TITLE
Export of a map containing a WMTS layer like an image

### ISSUE THREAD

**Issue by alexCCI** [qgis/pyqgis#119]
Hello,
I have a problem with the export of a map which contain a WMTS layer.

By this method i add the WMTS layer in my map:

def raster(self):
    self.urlWithParams = "type=xyz&url=http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/%7Bz%7D/%7By%7D/%7Bx%7D&zmax=20&zmin=0&http-header:referer=Requires%20ArcGIS%20Onlinesubscription"
    self.rlayer = QgsRasterLayer(self.urlWithParams, 'fond_carto', 'wms')
    self.project.addMapLayer(self.rlayer)
    
After i add another elements and i try to make the export like an image:

self.fn = "C:/Users/Stagiaire04/Desktop/INSEE_Shiny_app/gis_output/" + self.map_name + '.jpeg'
self.exporter.exportToImage(self.fn, QgsLayoutExporter.ImageExportSettings())

Finally i have this error:

QObject::connect: Cannot queue arguments of type 'QgsNetworkRequestParameters'
(Make sure 'QgsNetworkRequestParameters' is registered using qRegisterMetaType().)  

If i change the layer by a WMS and not WMTS it works
For example self.urlWithParams = "crs=EPSG:2154&dpiMode=7&format=image/png&layers=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&styles&url=https://wxs.ign.fr/essentiels/geoportail/r/wms?" doesn't return any error

PS I work under QGIS 3.28 LTR

Does anyone now how can i resolve this problem?

Thanks

**Comment by 3nids** [comment]
This repo is for the API documentation. 
You can head to https://gis.stackexchange.com/ or the QGIS developer mailing list.
