### ISSUE TITLE
Missing paragraph between "new in" and "methods"

### ISSUE THREAD

**Issue by nyalldawson** [qgis/pyqgis#12]
See eg http://python.qgis.org/master/core/Layout/QgsLayoutItemLabel.html

The class docs start with:

"A layout item subclass for text labels.

New in version 3.0: Methods"

This makes it seem like the following methods were added in version 3 - when it's actually the class which was new in 3.0, and the ":" should be removed and replaced with a new paragraph instead.

Seems to happen with all classes marked with a since annotation

**Comment by DelazJ** [comment]
@3nids, looks like this is fixed https://qgis.org/pyqgis/master/core/QgsLayoutItemLabel.html
