### ISSUE TITLE
Problem with OpenLayers plugin

### ISSUE THREAD

**Issue by QwertyS98** [qgis/pyqgis#124]
when I try to use every possible Map Layer from OpenLayers plugin this error come and the Maps doesn't work as it should and this comment shows up:

NotImplementedError: QgsPluginLayer.setTransformContext() is abstract and must be overridden 

Versione Python: 3.9.5 (default, Sep 10 2021, 16:18:19) 

How can I fix this problem?

**Comment by gioman** [comment]
@QwertyS98 This must be filed in the Openlayers plugin tracker, not here.
