### ISSUE TITLE
Missing providers when only qgis is installed in a conda env

### ISSUE THREAD

**Issue by r9zzai** [qgis/pyqgis#130]
If a conda env is used only providers like postgres are missing.

There is a discussion here [here](https://gis.stackexchange.com/a/469269) where i answered.

If there is no local qgis installation only pyqgis with conda, is it possible to set the postgis provider class so that a layer shows not none as a provider if a postgis layer is called within pyqgis reading a project. The libprovider_postgres.so file is created in env/lib/qgis when installing qgis within a conda env. So the resources for the postgres provider should be available.

I tried also to set the `LD_LIBRARY_PATH` environmental variable within the py script to `env/lib/qgis` as stated [here](https://docs.qgis.org/3.28/en/docs/pyqgis_developer_cookbook/intro.html) but `QgsProviderRegistry.instance().providerList()` shows only `['gdal', 'memory', 'mesh_memory', 'ogr', 'vectortile']`.

Is it possible to use postgres provider with pyqgis in a conda env where is no local qgis is installed?

**Comment by 3nids** [comment]
This repo is for the Python API documentation. Please report this issue to https://github.com/qgis/QGIS/issues/new/choose
