### ISSUE TITLE
Deprecated note Qgs3DMapScene

### ISSUE THREAD

**Issue by AbdelghaniTamort** [qgis/pyqgis#139]
In version 3.36 docs there is a note that says that Qgs3DMapScene class isn't available in Python Bindings, even though it is accessible. 
![Qgs3dMapScene](https://github.com/qgis/pyqgis/assets/118017108/b5c24707-0db6-4d83-b07e-afc89fc47989)

**Comment by DelazJ** [comment]
This is due to the PyQGIS docs build being broken for almost two weeks.
@3nids Any idea how to fix that PEP 668 issue? I'm interested for the docs repo also.

**Comment by rduivenvoorde** [comment]
I think the build is "fixed' now. Not sure if the original issue is though:

https://qgis.org/pyqgis/master/_3d/Qgs3DMapScene.html#module-Qgs3DMapScene
