### ISSUE TITLE
Identify sliver polygons and assign each to the neighboring polygon that shares the same attribute value such as block ID

### ISSUE THREAD

**Issue by wfw119** [qgis/pyqgis#21]
I know there's a feature in QGIS to eliminate sliver polygons and it can also be implemented in standalone script. It seems like a blackbox to get the results directly. Is there a way in standalone script to identify (extract) sliver polygons? Also, can I use other parameters (e.g. the neighboring polygon that shares the same attribute value such as block ID) not the ones given in QGIS to assign slivers?

Thanks!

**Comment by 3nids** [comment]
@wfw119 sorry, this repo is meant for the documentation. Please report any issue to https://issues.qgis.org/projects/qgis/issues/ or ask question on the mailing lists https://www.qgis.org/en/site/getinvolved/mailinglists.html
