### ISSUE TITLE
Incorrect return type when %MethodCode present

### ISSUE THREAD

**Issue by nyalldawson** [qgis/pyqgis#25]
E.g. see QgsFeature::attribute( int fieldIdx ). In this case the MethodCode requires the sip definition to use SIP_PYOBJECT as the return type, but this prevents the docs from showing the actual return type and only "object" is used.

**Comment by 3nids** [comment]
this one might be hard to tackle because the signature is automatically created.
What would you expect to be written in such case? QVariant?

**Comment by nyalldawson** [comment]
That's perhaps a poor example. Here's a better one: https://github.com/qgis/QGIS/pull/8542/files#diff-c1555f0de08a3bfc1af9e9ce10d7e4b8R104

In this case the result will always be a QgsPoint

**Comment by 3nids** [comment]
but why do you you use SIP_PYOBJET instead of QgsPoint directly?

**Comment by 3nids** [comment]
well the only way I see is to manually write the signature in the docstring.
It would also require to modify docstring directive:
```%Docstring(signature=discarded)```

**Comment by 3nids** [comment]
I see no way to hack SIP's generation of signatures to integrate custom return types.

**Comment by 3nids** [comment]
good catch.
You'll (just) need to add SIP_TYPEHINT to qgis_sip.h and adapt sipify.pl
