### ISSUE TITLE
3.6 link missing on index page

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/pyqgis#31]
3.6 docs are available, but on index page (https://qgis.github.io/pyqgis/ or https://qgis.org/pyqgis) the link to it is not yet added

I think I should be able to fix it myself, or do a PR but fail to find the page...

Maybe also add a link to https://github.com/qgis/pyqgis on the bottom of the index page?

**Comment by rduivenvoorde** [comment]
@3nids can you point me to the source of the index page? So I can try to add the 3.6 docs and link to this repo?

**Comment by 3nids** [comment]
done here a2cde7b48c318a64702fafeed7465355ff13eb5d

**Comment by rduivenvoorde** [comment]
Ah, duh. Me bad, I was looking into the other directories. 

Thanks!

Is it ok if I add some more styling, and maybe a link to this repo?

**Comment by 3nids** [comment]
feel free, you are actually the original creator of this page ;)
