### ISSUE TITLE
Problem showing tables at docs.

### ISSUE THREAD

**Issue by kylefelipe** [qgis/pyqgis#36]
Hi, i have been studing PyQgis docs and i found something.
Some descriptions are bigger than cell, that needs a scroll to see all description.

![image](https://user-images.githubusercontent.com/24795382/64495933-f2eaee00-d275-11e9-885a-3dfd2005067e.png)

Maybe, can it set at CSS or html from the theme to make a line break.

I have tested in chrome and firefox.

**Comment by MrChebur** [comment]
Description text does not fit into the `Methods` table. It may be worth adding a scroll bar or setting up text wrapping on the new line.
GIF Animation of the issue: https://i.ibb.co/cLxSmwr/Cj-Vi-Zr-Lqd9.gif

Page URL: https://qgis.org/pyqgis/master/core/QgsProject.html
Other versions are affected too i.e.: https://qgis.org/pyqgis/3.4/core/QgsProject.html

**Comment by DelazJ** [comment]
@3nids overriding rtd default theme with code at https://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html#table-width-fix-for-read-the-docs-sphinx-theme seems to fix the issue (tested on another project)

**Comment by DelazJ** [comment]
@3nids any reason the fix for a larger table in 6ad2e47 was never merged in the repo?

**Comment by 3nids** [comment]
I don't recall.
We could give it another try with a PR (we'll have an URL with results)
