### ISSUE TITLE
Use OpenCV in PyQGIS

### ISSUE THREAD

**Issue by Spatialghost** [qgis/pyqgis#42]
I developing QGIS module and I have a question, how to capture QgsMapCanvas window with OpenCV for shoving in different frame or different application?
OpenCV will have data from map view window, in my case raster data for interactive processing and show processed picture in other frame.

**Comment by alexbruy** [comment]
Bugtracker used only for bugreports and feature requests. Such questions should be asked in the mailing list or other support channel.
