### ISSUE TITLE
QgsLayerTreeGroup.clone(self) doesn't clone children

### ISSUE THREAD

**Issue by MatthiasHinz** [qgis/pyqgis#43]
The clone-Method of QgsLayerTreeGroup doesn't seem to work as expected. According to the documentation for QGIS 3.10 (and also current master) the children are cloned as well. However, when cloning a group with of map layers, the layers of the clone just seems to be references to the originals. Any changes applied to the supposedly cloned layer are also applied to the original.

From the documentation:
> clone(self) → QgsLayerTreeGroup
>    Returns a clone of the group. The children are cloned too.
>    Return type
>        QgsLayerTreeGroup

https://qgis.org/pyqgis/master/core/QgsLayerTreeGroup.html?#qgis.core.QgsLayerTreeGroup.clone

Code Sample:
```
root = iface.layerTreeCanvasBridge().rootGroup()
group1 = QgsLayerTreeGroup('group 1')
layer1 = QgsVectorLayer("path" , "layer name 1")
group1.addLayer(layer1)
root.addChildNode(group1)
group2 = group1.clone()
group2.setName("group 2")
layer2 = group2.children()[0]
layer2.setName("layer name 2")
root.addChildNode(group2)
```
This code will result into the following layer-structure. In this example, layer2 is renamed, but renaming (as way as any other changes) also affects layer1

- group 1
   - layer name 2
- group 2
   - layer name 2

```
QGIS-Version | 3.10.0-A Coruña
BS-Version | Ubuntu 19.10
```

**Comment by nyalldawson** [comment]
Cloning a layer tree node is not supposed to clone the underlying layer itself. It's just a copy of the **node**. There's a different method in QgsMapLayer for creating a clone of an actual map layer.
