### ISSUE TITLE
Rendering of brewer palette not readable (?)

### ISSUE THREAD

**Issue by DelazJ** [qgis/pyqgis#44]
I wonder if the rendering of the [brewer_string](https://qgis.org/pyqgis/master/core/QgsColorBrewerPalette.html) is as expected
![image](https://user-images.githubusercontent.com/7983394/72721271-f2475a00-3b7b-11ea-963d-c2401be896f5.png)

**Comment by 3nids** [comment]
hmmm, I don't really know what to do here. Any idea?

**Comment by DelazJ** [comment]
TBH, not really. Sorry!
I guess these are colors of each palette. Maybe make the `\n` actually behave as an end of line? Will result in a looong list of colors however. Or as a table of 2/3 columns. Saying that, I have no idea what it takes to make it...
Or just ignore. I'm not sure it's something in the API people would (frequently enough) use. So other than being ugly and unreadable, it does not really harm.
