### ISSUE TITLE
Missing code sample

### ISSUE THREAD

**Issue by DelazJ** [qgis/pyqgis#46]
Not sure whether I should open it here or in the source repository

There should probably be code sample converted [here](https://qgis.org/pyqgis/master/core/QgsRasterLayer.html)

![image](https://user-images.githubusercontent.com/7983394/72723728-b2837100-3b81-11ea-8934-9d1d456ad4d6.png)

as we can see in the [source .h file](https://github.com/qgis/QGIS/blob/master/src/core/raster/qgsrasterlayer.h) (missing in the sip.in one)

![image](https://user-images.githubusercontent.com/7983394/72723842-02face80-3b82-11ea-9839-517a3f33bc3f.png)

**Comment by 3nids** [comment]
The code is cpp, they are not shown in PyQGIS docs.

**Comment by DelazJ** [comment]
I thought there were some magic that converted them into Python, as I've seen Python code samples but they probably were Python ones in the source already.
Still, it's weird to announce `Sample usage of the QgsRasterLayer class:` and then no sample...

**Comment by 3nids** [comment]
@DelazJ  indeed.
Shall we put the line as a comment in the code snippet?

**Comment by DelazJ** [comment]
>  Shall we put the line as a comment in the code snippet?

Will the codes be rendered in the C++ API doc if they are in python? If yes, and if it is usable to have python code in c++ api, then @nyalldawson [suggestion](https://github.com/qgis/QGIS/pull/37556#issuecomment-653677899) to move all codes to python would fix this I think.
Otherwise, yes we probably better put them as code comments.

**Comment by 3nids** [comment]
yes, python code is shown.
So yes, except if we have a very valid reason to do so, we should enforce python
