### ISSUE TITLE
Inconsistencies in QGIS Python API documentation pages

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/pyqgis#52]
## Description

In QGIS Python API documentation pages there are same inconsistencies among various versions:

for **master, 3.10 and 3.4**:

![image](https://user-images.githubusercontent.com/16253859/77742829-63413d00-7017-11ea-90d8-11571e1a13cd.png)

![image](https://user-images.githubusercontent.com/16253859/77741827-d1850000-7015-11ea-85e7-a3e61f2856b6.png)

for **3.8, 3.6, 3.2, 3.0**:

![image](https://user-images.githubusercontent.com/16253859/77742752-43117e00-7017-11ea-97b2-7e76873218f6.png)

![image](https://user-images.githubusercontent.com/16253859/77742361-abac2b00-7016-11ea-911a-2fcb9a0ea406.png)

**Comment by 3nids** [comment]
there is a script to run to fix these but apparently not working as expected
https://github.com/qgis/pyqgis/blob/master/scripts/publish-docs.sh#L42-L51

thanks for reporting, not sure when I'll get back to this

**Comment by agiudiceandrea** [comment]
Hi @3nids, probably the part of the script you added in October 2019 https://github.com/qgis/pyqgis/commit/52886ba24847f2bf9e2663f499cca4756890f900 works fine, but the QGIS Python API docs online for 3.6 and 3.8 versions were updated only on June/September 2019 and for 3.0 and 3.2 on April/August 2018.

Could that be the problem?

**Comment by 3nids** [comment]
a new script has been added and run which should fix this.
results will be available within next hour or so.
