### ISSUE TITLE
processing.algorithmHelp from terminal (outside QGIS desktop)

### ISSUE THREAD

**Issue by FrancoisChaumont** [qgis/pyqgis#53]
Environment:
- Ubuntu 18.04.4
- QGIS 3.12.1-București
- python 3.6.9

No matter which provider:algorithm algorithmHelp is trying to display details for it seems to encounter the same issue when running from terminal outside of QGIS desktop.

```
Create grid (native:creategrid)
...
CRS: Grid CRS

        Parameter type: QgsProcessingParameterCrs

        Accepted data types:
Traceback (most recent call last):
    ...
    processing.algorithmHelp("native:creategrid")
  File "/usr/share/qgis/python/plugins/processing/tools/general.py", line 75, in algorithmHelp
    print('\n'.join(opts))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2026' in position 94: ordinal not in range(128)
```

**Comment by 3nids** [comment]
This is the docs repository and not QGIS repository.
This should be reported here: https://github.com/qgis/QGIS/issues

**Comment by FrancoisChaumont** [comment]
> This is the docs repository and not QGIS repository.
> This should be reported here: https://github.com/qgis/QGIS/issues

Thank you @3nids
