### ISSUE TITLE
Headings stripped from docs

### ISSUE THREAD

**Issue by nyalldawson** [qgis/pyqgis#56]
See e.g. https://qgis.org/pyqgis/master/core/QgsTriangle.html 

The "Example" headings from methods like isDegenerate() do not show

**Comment by 3nids** [comment]
this seems to be fixed: https://qgis.org/pyqgis/master/core/QgsTriangle.html#qgis.core.QgsTriangle.isDegenerate
from your commit I guess: https://github.com/qgis/QGIS/commit/a5101f2ade0a89ad6477d6bb6ec1a71b99c6d761#diff-af71b967900643f18b488d5c854a7531R120

feel free to re-open if you spot anything else
