### ISSUE TITLE
QgsLogger() does not output anything

### ISSUE THREAD

**Issue by tschmetzer** [qgis/pyqgis#61]
Dear developers,

I am developing some code in the QGIS Python Console. As I cannot set any breakpoints and print cannot be used due to multithreading I tried to use the QgsLogger class as described in the documentation. Unfortunately I couldn't get any output. Also there are no examples or comments regarding this topic in any public GIS related user group.
I even tried to set some environment variables in order to force the logging which didn't work out.

This is the code I use:

from qgis.core import QgsLogger

logname= "c:/temp/test.log"

# Set environment variables
os.environ['QGIS_LOG_FILE'] = logname
os.environ['QGIS_DEBUG'] = '3'

print ("Logfile: ",QgsLogger.logFile())
QgsLogger.critical("QgsLoggerTest1")
QgsLogger.debug("QgsLoggerTest2")

QgsLogger.logMessageToFile("Mymessage")
print ("Debuglevel: ",QgsLogger.debugLevel())

The output in the console is as follows:

Logfile:  
Debuglevel:  0

No file was created in c:/temp/test.log nor was the output written to any tab in the log messages window.

In the regarding QGIS documentation https://docs.qgis.org/3.10/en/docs/pyqgis_developer_cookbook/communicating.html#logging there is a link to https://qgis.org/pyqgis/3.10/core/QgsLogger.html#qgis.core.QgsLogger where the first sentence clearly states "QgsLogger is a class to print debug/warning/error messages to the console" which does not happen.

I'm running the following system:
QGIS version | 3.14.1-Pi | QGIS code revision | de08d6b
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | GroupStats; nominatim; QuickOSM; db_manager; MetaSearch; processing

Please note that I had opened an issue at the QGIS bug tracking site as well as I didn't know pyqgis has it's own site:
https://github.com/qgis/QGIS/issues/38188

I had also set up a bug report for documentation at https://github.com/qgis/QGIS-Documentation/issues/5995

As soon as we're sure what's the reason for the failure and that this site here is the correct one where to handle the bug I suggest to close it where obsolete.

**Comment by 3nids** [comment]
This repo is for the PyQGIS documentation.
Please fill the issue in the QGIS repo https://github.com/qgis/QGIS/issues/new/choose
