### ISSUE TITLE
An asterisk is erroneously present at the end of some sentences

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/pyqgis#62]
For example in https://qgis.org/pyqgis/master/core/QgsLogger.html

![image](https://user-images.githubusercontent.com/16253859/89714753-59eeb680-d9a1-11ea-9e45-be96f01c3d2f.png)

The asterisks are not present in the API documentation https://qgis.org/api/classQgsLogger.html

**Comment by 3nids** [comment]
fixed
