### ISSUE TITLE
same wkbType ID for polygons and unknown geometry

### ISSUE THREAD

**Issue by riccardoklinger** [qgis/pyqgis#66]
the documentation for qgis.core.QgsWkbTypes shows different IDs depending on the wkbType. Link: [Documention](https://qgis.org/pyqgis/master/core/QgsWkbTypes.html)
Unfortunately the id for polygons is the same as for unknownGeometry which is 3:
![grafik](https://user-images.githubusercontent.com/7377897/99920736-c493ea00-2d25-11eb-885b-0c05b46c7f85.png)

**Comment by gioman** [comment]
@riccardoklinger maybe this is better suited for the main (QGIS application) bug tracker?

**Comment by 3nids** [comment]
This refers to 2 distinct enums: Type vs GeometryType. see https://qgis.org/api/classQgsWkbTypes.html
Sadly, in current situation of Python bindings we cannot do better in the PyQGIS docs.
Situation should be improved in next major upgrade.
