### ISSUE TITLE
https://qgis.org/pyqgis/3.20/ does not work (404 not found)

### ISSUE THREAD

**Issue by MrChebur** [qgis/pyqgis#77]
https://qgis.org/pyqgis/3.20/ does not work (404 not found), while [master ](https://qgis.org/pyqgis/master/)and [3.18](https://qgis.org/pyqgis/3.18/) work fine.

![firefox_ZGKa4rZugp](https://user-images.githubusercontent.com/20655102/125905269-9c13da27-2ee3-4fdb-8a48-048848f730c2.png)

**Comment by rduivenvoorde** [comment]
Is ok, now.
Thanks
