### ISSUE TITLE
Problems with StartUp.py

### ISSUE THREAD

**Issue by Nobel9** [qgis/pyqgis#79]
I want to manipulate my QGIS 3.16.9 with the startup.py.

It works fine, for the most things but there are a few errors (?).

For example i want to edit the Main Window Title and the Man Window Icon with:

`from qgis.utils import iface`
`from qgis.PyQt.QtGui import QIcon`
`iface.mainWindow().setWindowTitle('New Title')`
`iface.mainWindow().setWindowIcon(QIcon(iconpath))`

When i start QGIS the Icon is changed but the Title isnt. When i run the startup.py again in QGIS the Window Title changes.

I've got the same problem when i tried to remove all Menus from QGIS in the startup.py. It works for all but database- and processing-Menu. Running the script in QGIS again, also these two menus are away.

Is there a method for running the code when QGIS finished starting? I think startup.py runs before, that could be the problem (?)

Thanks for help

**Comment by rduivenvoorde** [comment]
Sorry, this is the issue tracker for the pyqgis api website. This kind of questions is better asked on QGIS dev or user mailing list:
https://qgis.org/en/site/getinvolved/mailinglists.html

Closing this one here.
