### ISSUE TITLE
3.22 build missing

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/pyqgis#83]
Anybody can maybe write down in the readme how to add a new version of the pyqgis pages for 3.22 and higher?

Then anybody with enough github power can take that task?

**Comment by 3nids** [comment]
looks like you had enough power :)

**Comment by rduivenvoorde** [comment]
Huh, only thing I have done is update this file:

https://github.com/qgis/pyqgis/blob/gh-pages/index.html

I would not have thought that that would make 3.22 build (honestly yesterday there was no https://qgis.org/pyqgis/3.22/ yet...

Some magic going on? Or did you silently started something :-)

**Comment by 3nids** [comment]
I did the changes to build 3.22 yesterday but actually forgot to update the page. I'll try to automate this.

**Comment by DelazJ** [comment]
@3nids Seems that there is no build for 3.26 https://qgis.org/pyqgis/3.26/ although it is referenced in many places
