### ISSUE TITLE
loadNamedStyle not loading files beginning with certain letters

### ISSUE THREAD

**Issue by stevetb777** [qgis/pyqgis#84]
A .qml with categorized symbology and labels was not loading when using:
layer.loadNamedStyle('path\to\file.qml')    
layer.triggerRepaint()

After a couple of hours of investigation and starting out with much more complex ideas about why this might not be working, I concluded the problem was simply the first letter of the filename.

This issue existed even with a simple fill:
[b-simple-fill.zip](https://github.com/qgis/pyqgis/files/8064714/b-simple-fill.zip)
b-simple-fill will not load, but renaming it to p-anything will. 

I have not tested the entire alphabet.  If I name the files starting with a p, w, or z they load.  If I name them starting with f, a, t, r, b they do not load.

Here are my notes from my tests to conclude this:
- parcel_outline.qml loads
- floods.qml does NOT load
- copied parcel_outline.qml file to parcel_outline2.qml to experiment with
- parcel_outline2.qml loads still
- opened both in notepad, copied contents of floods.qml and pasted into parcel_outline2.qml - LOADS
- renamed parcel_outline2.qml to floods.qml.  Does NOT load.
- renamed floods.qml to parcel-outline2.qml (hypen instead of underscore).  LOADS
- renamed original floods.qml to parcel-outline2.qml - LOADS
- renamed original floods.qml to floodflood_floods.qml (longer title) - does NOT load
- renamed to parcel-outline-dude.qml - LOADS
- renamed to rabid-bunny-rabbit.qml - does NOT load
- renamed to parcel-outlane.qml - LOADS
- renamed to barker-outlane.qml - does NOT load
- renamed to pretty-outlane.qml - LOADS
- tretty-outlaneeee.qml does NOT load
- pattycake.qml LOADS
- patty.qml LOADS
- fatty.qml does NOT LOAD
- tatty.qml does NOT load
- batty.qml does NOT load
- pat.qml LOADS
- p.qml LOADS
- pfloods.qml LOADS
- w.qml LOADS
- f.qml does NOT load
- a.qml does NOT load
- z.qml LOADS

Note that these load when applying the style via the GUI regardless of the file name.

Thank you for all you do!

**Comment by nyalldawson** [comment]
> layer.loadNamedStyle('path\to\file.qml')

You need to use "/" slashes in paths, even on windows. Try

    layer.loadNamedStyle('path/to/file.qml')

"something\bxxx.qml"  is interpreting "\b" as a "backspace" character. See https://docs.python.org/3/reference/lexical_analysis.html#strings .

**Comment by stevetb777** [comment]
Youch... makes perfect sense now.  Thank you so much!
