### ISSUE TITLE
extract points coordinates from vector layer in a standalone PyQGIS script in Ubuntu

### ISSUE THREAD

**Issue by alikataal** [qgis/pyqgis#86]
I am running a PyQGIS script (QGIS 2.18.17) on the Ubuntu terminal to import a CSV file that includes the latitude and longitude of several points and create a polygon from them. 

I can import the CSV file as a vector layer, but I don't know how to extract the coordinates of the points and create the polygon from them (I wrote a similar script in the PyQGIS console in the windows version, and I used the iface.activeLayer() to select the active layer and read points coordinates (https://gis.stackexchange.com/questions/425603/how-to-create-a-polygon-from-a-csv-file-with-coordinates-using-pyqgis)). But iface does not work in the standalone script and I don't know how to do it).

Here is the script in Ubuntu:

```
#!/usr/bin/python
import sys,os,glob
from qgis.core import *
from PyQt4.QtCore import *
from PyQt4.QtGui import *

QgsApplication.setPrefixPath('/usr', True)
qgs = QgsApplication([], False)
qgs.initQgis()

# Put your pyqgis code here:
uri = "file:////home/aka000/site4/PyQGIS/Tailings_Pond_1A.csv?encoding=%s&delimiter=%s&xField=%s&yField=%s&crs=%s" % ("UTF-8",",", "Lat", "Long","epsg:4326")

#Make a vector layer
eq_layer=QgsVectorLayer(uri,"eq-data","delimitedtext")

#Check if layer is valid
if not eq_layer.isValid():
    print ("Layer not loaded")

#Add CSV data    
QgsMapLayerRegistry.instance().addMapLayer(eq_layer)

idx=eq_layer.getFeatures()

for f in idx:
    point=QgsPointXY(f['long'], f['lat'])
```
And this is the error I get:

```
point=QgsPointXY(f['long'], f['lat'])
NameError: name 'QgsPointXY' is not defined
```

**Comment by nyalldawson** [comment]
This is not the right place to ask questions like this
