### ISSUE TITLE
QgsSpatialIndex docs not helpful; what does nearestNeighbor return?

### ISSUE THREAD

**Issue by velle** [qgis/pyqgis#91]
Regarding: https://qgis.org/pyqgis/3.2/core/other/QgsSpatialIndex.html

I don't know how this documentation is produced. Perhaps its written by a human or perhaps its autogenerated in some way, maybe from the C++ code. 

In any case, the documentation simply says that it returns "object", which is quite unhelpful. It returns a list of integers, where each integer represents an id of an object. I still havent figured out exactly where this id come from.

**Comment by DelazJ** [comment]
Hi @velle 
> Regarding: https://qgis.org/pyqgis/3.2/core/other/QgsSpatialIndex.html

If you are really using 3.2, there is nothing more we can do with that. This is an old and unmaintained version; you might want to look at https://qgis.org/pyqgis/master/core/QgsSpatialIndex.html
> Perhaps its written by a human or perhaps its autogenerated in some way, maybe from the C++ code.

BINGO! Generated from C++ code written by human
> In any case, the documentation simply says that it returns "object", which is quite unhelpful. It returns a list of integers, where each integer represents an id of an object. I still havent figured out exactly where this id come from.

For questions, you might be better served on the qgis-developers mailing list (see our [support channels](https://qgis.org/en/site/forusers/support.html)). For bug or missing details in the docs, you should report where the C++ code is being written, that is https://github.com/qgis/QGIS/issues.
This repository is mainly to manage the build of the PyQGIS documentation.

**Comment by marcu** [comment]
Hello @velle 

That MR ( https://github.com/qgis/QGIS/pull/52831 ) will improve the signature of the functions in the python doc. The change will appear when the doc will be regenerated. So I think we can close that issue (@DelazJ )

Thanks a log for the bug report. If you discover similar problems do not hesitate to report it, it is very helpful.
