### ISSUE TITLE
Style rule based on variable not working in QGIS 3.22

### ISSUE THREAD

**Issue by jfvilleforceix** [qgis/pyqgis#92]
I'm using a QGIS style based on a function which returns the value of a layer variable passed through a pyqgis plugin :

```
@qgsfunction(args="auto", group="")
def color_trajecto(feature, parent, context):
    color = context.variable("color")
    return color if color else "#ff0000"
```

Then I put this as entry of an expression for filling the color of my symbol as shown below :
![2022-06-21 10_39_41-Éditer une règle](https://user-images.githubusercontent.com/29303942/174757407-29907af4-133a-48d0-9cdf-dd4ee7654b40.png)

Default value is red, but I passed blue and it is well detected in the filling color bar on its left. But above the color is not taken into account and the symbol as well. This code is working until QGIS 3.16 therefore I presume it's an issue of 3.22.

**Comment by DelazJ** [comment]
@jfvilleforceix sorry for the late feedback. Issues with QGIS use should be reported at https://github.com/QGIS/issues. This repository is for the PyQGIS **documentation** management. Thanks.

**Comment by jfvilleforceix** [comment]
I asked it here : https://github.com/qgis/QGIS/issues/49106

**Comment by DelazJ** [comment]
Great!
